from time import *
num1=1
num2=1
print("-----------multiplication table-----------")
while num1<13:
    print("\n")
    while num2<13:
        if num1*num2<10:
            print(num1*num2,end="---")
        elif num1*num2>9 and num1*num2<100:
            print(num1*num2,end="--")
        elif num1*num2>99:
            print(num1*num2,end="-")
        num2+=1
    num1+=1
    num2=1
if int(input("\n1:to save\n0:to exit")):
    myfl=open("multiplication table.txt",'w')
    num1=1
    num2=1
    myfl.write("-----------multiplication table-----------")
    while num1<13:
        myfl.write("\n")
        while num2<13:
            if num1*num2<10:
                myfl.write(str(num1*num2)+"---")
            elif num1*num2>9 and num1*num2<100:
                myfl.write(str(num1*num2)+"--")
            elif num1*num2>99:
                myfl.write(str(num1*num2)+"-")
            num2+=1
        num1+=1
        num2=1
    myfl.write("\ngenerated by multiplication table.py")
    myfl.close()
else:
    print("exiting")
    sleep(3)
